name: C Clients CI
on:
  push:
    branches:
      - eventbus_clients_ci_tests
defaults:
  run:
    working-directory: C
jobs:
  Build_C_Clients:
    name: Build C Clients
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run build
        run: bash -x build.sh --notty --dist
      - name: list dist
        run: ls -l dist
      - name: Get project version
        run: echo "PROJECT_VERSION=$(cat VERSION)" >> $GITHUB_ENV
