name: C Clients CI
on:
  push:
    branches:
      - eventbus_clients_ci_tests
defaults:
  run:
    working-directory: C
jobs:
  Build_C_Clients:
    name: Build C Clients - ${{ matrix.CROSS_TRIPLE }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
#        CROSS_TRIPLE: [x86_64-linux-gnu, i686-w64-mingw32, x86_64-w64-mingw32, x86_64-apple-darwin]
        CROSS_TRIPLE: [x86_64-w64-mingw32]

    steps:
      - uses: actions/checkout@v2
      - name: Install mingw packages
        run: apt-get install -y build-essential gcc-mingw-w64-x86-64
      - name: Run make build for x86_64-w64-mingw32
        run: bash -x build.sh
      - name: list targets
        run: ls -l target
