name: Go CI
on:
  push:
    branches:
      - master
    paths:
      - .github/**
      - Go/**
  pull_request:
    branches:
      - master
    paths:
      - .github/**
      - Go/**
  schedule:
    - cron:  '* 4 * * *'
jobs:
  Build_Go_Client:
    name: Build Go Client
    runs-on: ubuntu-latest
    container:
      image: golang:latest
      volumes:
        - ${{ github.workspace }}/Go:/workdir:Z
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run build
        run: bash -x /workdir/build.sh
