name: Node CI
on:
  push:
    branches:
      - master
    paths:
      - .github/**
      - nodejs/**
  pull_request:
    branches:
      - master
    paths:
      - .github/**
      - nodejs/**
  schedule:
    - cron:  '* 4 * * *'
jobs:
  Build_NodeJs_Client:
    name: Build Nodejs Client
    runs-on: ubuntu-latest
    container:
      image: node:alpine
      volumes:
        - ${{ github.workspace }}/nodejs:/workdir:Z
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run build
        run: bash -x /workdir/build.sh
      - name: Get project version
        run: echo "PROJECT_VERSION=$(head -n 5 package.json |grep "version"|cut -d "\"" -f4)" >> $GITHUB_ENV
      - name: Deploy to Bintray
        if: ${{ github.repository_owner == 'vert-x3' && github.event_name == 'push' && !endsWith(env.PROJECT_VERSION, '-SNAPSHOT') }}
        run: |
          curl -T vertx3-tcp-eventbus-client-${{ env.PROJECT_VERSION }}.tgz -u${{ secrets.APIKEY }} https://api.bintray.com/content/vertx/vertx-eventbus-bridge-clients/node/${{ env.PROJECT_VERSION }}/vertx3-tcp-eventbus-client-${{ env.PROJECT_VERSION }}.tgz
