name: Python CI
on:
  push:
    branches:
      - master
    paths:
      - .github/**
      - python/**
  pull_request:
    branches:
      - master
    paths:
      - .github/**
      - python/**
  schedule:
    - cron:  '* 4 * * *'
defaults:
  run:
    working-directory: /workdir
jobs:
  Build_Python_Client:
    name: Build Python Client
    runs-on: ubuntu-latest
    container:
      image: python:alpine
      volumes:
        - ${{ github.workspace }}/python:/workdir:Z
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run build
        run: |
          ls -l
          pwd
          ls -l /workdir
          bash -x python/build.sh
      - name: Get project version
        run: echo "PROJECT_VERSION=$(cat setup.py |grep "version="|cut -d "'" -f2)" >> $GITHUB_ENV
      - name: Deploy to Bintray
        if: ${{ github.repository_owner == 'vert-x3' && github.event_name == 'push' && !endsWith(env.PROJECT_VERSION, '-SNAPSHOT') }}
        run: |
          curl -T dist/Vertx-${{ env.PROJECT_VERSION }}.tar.gz -u${{ secrets.APIKEY }} https://api.bintray.com/content/vertx/vertx-eventbus-bridge-clients/python/${{ env.PROJECT_VERSION }}/Vertx-${{ env.PROJECT_VERSION }}.tar.gz
