name: Python CI
on:
  push:
    branches:
      - eventbus_clients_ci_tests
  pull_request:
    branches:
      - eventbus_clients_ci_tests
jobs:
  Build_Python_Client:
    name: Build Python Client
    runs-on: ubuntu-latest
    container:
      image: python:alpine
 #     volumes:
 #       - ${{ github.workspace }}/python:/workdir:Z
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run build
        run: |
          echo -e "link to /workdir"
          ln -s ${{ github.workspace }}/python /workdir
          echo -e "list current dir"
          ls -l 
          echo -e "list root dir /"
          ls -l /
          echo -e "list workdir /workdir"
          ls -l /workdir
          echo -e "execute /workdir/build.sh"
          cat /workdir/build.sh
          bash -x /workdir/build.sh
