name: Python CI
on:
  push:
    branches:
      - eventbus_clients_ci_tests
  pull_request:
    branches:
      - eventbus_clients_ci_tests
defaults:
  run:
    working-directory: python
jobs:
  Build_Python_Client:
    name: Build Python Client
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run Python build
        run: python3 setup.py sdist
      - name: Check built result
        run: ls -l dist/
